apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: test-duckdns-cert
  namespace: default
spec:
  secretName: test-duckdns-tls
  dnsNames:
  - test.abhi-ckad.duckdns.org
  issuerRef:
    name: cert-manager-webhook-duckdns-production
    kind: ClusterIssuer